org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.248
mod_id=benssharks
mod_name=Dwurdy Sharks
mod_version=1.2.7
mod_license=LGPL-3.0
mod_authors=benndevs (original), Dwurdy (maintenance fork)
mod_description=A simplistic approach towards one of the ocean's most complex creatures. Community maintenance fork of Ben's Sharks.
